places = ['London','Newyork','Beijing']
print(places)
print(sorted(places))
print(sorted(places,reverse=True))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort()
print(places )